# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qatd_cpp_collocations <- function(texts_, types_, words_ignore_, count_min, sizes_, method, smoothing) {
    .Call(`_quanteda_textstats_qatd_cpp_collocations`, texts_, types_, words_ignore_, count_min, sizes_, method, smoothing)
}

qatd_cpp_manhattan <- function(A, margin = 1L) {
    .Call(`_quanteda_textstats_qatd_cpp_manhattan`, A, margin)
}

qatd_cpp_manhattan2 <- function(A, B, margin = 1L) {
    .Call(`_quanteda_textstats_qatd_cpp_manhattan2`, A, B, margin)
}

qatd_cpp_maximum <- function(A, margin = 1L) {
    .Call(`_quanteda_textstats_qatd_cpp_maximum`, A, margin)
}

qatd_cpp_maximum2 <- function(A, B, margin = 1L) {
    .Call(`_quanteda_textstats_qatd_cpp_maximum2`, A, B, margin)
}

qatd_cpp_canberra <- function(A, margin = 1L) {
    .Call(`_quanteda_textstats_qatd_cpp_canberra`, A, margin)
}

qatd_cpp_canberra2 <- function(A, B, margin = 1L) {
    .Call(`_quanteda_textstats_qatd_cpp_canberra2`, A, B, margin)
}

qatd_cpp_minkowski <- function(A, margin = 1L, p = 2) {
    .Call(`_quanteda_textstats_qatd_cpp_minkowski`, A, margin, p)
}

qatd_cpp_minkowski2 <- function(A, B, margin = 1L, p = 2) {
    .Call(`_quanteda_textstats_qatd_cpp_minkowski2`, A, B, margin, p)
}

qatd_cpp_keyness <- function(mt, measure, correct) {
    .Call(`_quanteda_textstats_qatd_cpp_keyness`, mt, measure, correct)
}

qatd_cpp_kwic <- function(texts_, types_, words_, pats_, window, delim_) {
    .Call(`_quanteda_textstats_qatd_cpp_kwic`, texts_, types_, words_, pats_, window, delim_)
}

qatd_cpp_set_meta <- function(object_, meta_) {
    invisible(.Call(`_quanteda_textstats_qatd_cpp_set_meta`, object_, meta_))
}

