# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_collocations <- function(texts_, types_, words_ignore_, count_min, sizes_, method, smoothing, thread = -1L) {
    .Call(`_quanteda_textstats_cpp_collocations`, texts_, types_, words_ignore_, count_min, sizes_, method, smoothing, thread)
}

cpp_keyness <- function(mt, measure, correct, thread = -1L) {
    .Call(`_quanteda_textstats_cpp_keyness`, mt, measure, correct, thread)
}

