# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qatd_cpp_collocations <- function(texts_, types_, words_ignore_, count_min, sizes_, method, smoothing) {
    .Call(`_quanteda_textstats_qatd_cpp_collocations`, texts_, types_, words_ignore_, count_min, sizes_, method, smoothing)
}

qatd_cpp_keyness <- function(mt, measure, correct) {
    .Call(`_quanteda_textstats_qatd_cpp_keyness`, mt, measure, correct)
}

qatd_cpp_set_meta <- function(object_, meta_) {
    invisible(.Call(`_quanteda_textstats_qatd_cpp_set_meta`, object_, meta_))
}

